# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_sav_region <- function(file_path, chrom, beg, end, fmt_str) {
    .Call('_savr_read_sav_region', PACKAGE = 'savr', file_path, chrom, beg, end, fmt_str)
}

